### PR TITLE
Features for a more responsive feel

### PR DESCRIPTION
**Pull request by firefish5000**
Thoughts
* If used smart_update should probably be renamed, perhaps auto_updater, auto_update_track?
* I am not sure of the best timeout to use for smart_update. A little after the track ends increases chances of us working in 1 shot, however with only 1 second accuracy, aiming right at the time likely gives us ~.6+ seconds after to ~.4- seconds before range, a guestimate 60%+ chance of having changed...

Current known issues
* smart_update's timer:stop should only be called when a timer is started to lower warnings in the logs, apparently '.started' may be used to test that.
* continuous_notify should probably be optional, if used. Since deleting/recreating the notify may cause slight flickering.
* I have not yet used scheduler, and cannot write timers for it.

### CODE REVIEW

**Comment by alexander-yakushev** [comment]
Also, I will be grateful if you change the indentation from tabs to spaces to match the general coding style.

**Comment by alexander-yakushev** [comment]
> I am not sure of the best timeout to use for smart_update. A little after the track ends increases chances of us working in 1 shot, however with only 1 second accuracy, aiming right at the time likely gives us ~.6+ seconds after to ~.4- seconds before range, a guestimate 60%+ chance of having changed...

I think it's fine to show the notification 1 seconds after the track has started. I think many players work like this.

**Comment by firefish5000** [comment]
Although slightly unrelated, a pause_after_current track command could also be nice. Running a command like os.execute(self:mpcquery() .. " -w current && " .. self:mpcquery() .. " pause &") on call. Or setting a var like do_pause_next to be checked on each track change.
Could be made so pause/play/stop and next/prev cancel it (kill process id). 
The pause_after function could also, determine if another mpd client has done something (ie. track change/seek) by monitoring track_position, and cancel the pause if the track changes when update_interval+5 seconds of time was still remaining. (suggesting since I am already writing it)

I am relatively comfortable with how its working now, so unless you find a problem/suggestion (maybe smart_update_timer should be nil unless started), would like pause_after functionality added to this, or a bug bites me(they usually wait for a proclamation of success), this should be it.
I am going to look at your unreleased awesompd over the weekend(onscreen widget sounds too interesting to wait for).
Also, this is my first pull request, so I am not sure of any sort or norms or formalities here. If I did something odd (eg. using fork's master branch for pull request), please inform me.

**Comment by alexander-yakushev** [comment]
Sorry for not responding — apparently Github doesn't send email notifications when new commits are added to the Pull Request. Note taken.

Regarding pause_after_current, this might be useful for someone, however it sounds like too much work to deeply integrate this with Awesompd (tracking changes, killing the process etc.). I doubt the feature would be used too often to care if user suddenly wants to disable it.

> I am going to look at your unreleased awesompd over the weekend(onscreen widget sounds too interesting to wait for).

Indeed it is. Here's how it looks like (bottom left corner): https://raw.githubusercontent.com/alexander-yakushev/awesomerc/master/themes/devotion/screenshot.png

> Also, this is my first pull request, so I am not sure of any sort or norms or formalities here. If I did something odd (eg. using fork's master branch for pull request), please inform me.

You are doing very well! Though I have a few tips. I would ask you to rewrite your branch and squash the fixes with the meaningful commits. Most maintainers prefer the pull request to contain only on-point commits, without commits that fix things in previous commits of the same pull request.

For this very reason it's usually a good idea to submit a PR from a non-master branch, because one should be prepared to rewrite and force-push the PR branch a lot. In case of master branch, this can screw up someone who uses that fork's master branch. But I don't think it's the case here, so you can safely rewrite the master branch of your fork.

**Comment by firefish5000** [comment]
Rebased into 3 commits.

**Comment by alexander-yakushev** [comment]
Looks good, thanks!

**Pull request merged**
